### ISSUE TITLE
Getting an Error: initializing

### ISSUE THREAD

**Issue by jasondrury** [diogo-fernan/ir-rescue#2]
Hi,

I am getting the following error (and it exits) when I execute "ir-rescue-win-v1.4.1.bat" on a Windows 10 machine.

  _initializing...
& was unexpected at this time._

Any idea what the problem could be?

Thanks.

**Comment by diogo-fernan** [comment]
Hi there,

Thanks for reporting this one. I forgot to remove one line from the initialization routine when removing RegRipper from the toolkit.

This has been fixed in v1.4.2 with https://github.com/diogo-fernan/ir-rescue/commit/708af2946b88a21980bccb51ec15132d2a1b74a7.

Can you check if the error persists with the fix?

**Comment by jasondrury** [comment]
It works now! Thanks a lot. This is a great resource!

**Comment by diogo-fernan** [comment]
Thanks. :-)
